baseURL = "https://lassesofus.github.io/Political_discussions/"
title = "Discussions on r/politics"
description = "Exam project in 02467"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Alexander Valentini", "Jakob Engel Ketmig", "Lasse Møller Sørensen"]
    notebook = "/Explainer_Notebook_FINAL.html"
    data = "https://drive.google.com/drive/folders/1UvzNpKcS7egE62V3mgZRvvcwSYdKZTii?usp=sharing"
    github = "https://github.com/JaQtae/SocInfo2022/tree/FinalProject"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"


