baseURL = "https://lassesofus.github.io/Website-template/"
title = "Discussions on r/politics"
description = "Exam project in "
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Henrik Nielsen", "Inga Jensen", "Mikkel Andersen"]
    notebook = "/explainer-notebook.html"
    data = "https://drive.google.com"
    github = "https://github.com/peterampazzo/project-website-template"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"

