baseURL = "https://lassesofus.github.io/Website-template/"
title = "Discussions on r/politics"
description = "Exam project in 02467"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Alexander Valentini", "Jakob Engel Ketmig", "Lasse Møller Sørensen"]
    notebook = "/explainer-notebook.html"
    data = "https://drive.google.com"
    github = "https://github.com/lassesofus/Website-template"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"


